<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>12</LangVersion>
    <AssemblyName>CopilotSecurity</AssemblyName>
    <RootNamespace>Secwest.CopilotSecurity.Gui</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CopilotSecurity.Core\CopilotSecurity.Core.csproj" />
    <ProjectReference Include="..\..\desktop\CopilotSecurity.Desktop\CopilotSecurity.Desktop.csproj" />
  </ItemGroup>
</Project>
